app = "qr-inventory-staging"
primary_region = "bom"
kill_signal = "SIGINT"
kill_timeout = "5s"
swap_size_mb = 512
[[vm]]
  size = "shared-cpu-1x"

[experimental]
auto_rollback = true

[deploy]
strategy = "rolling"

[env]
NODE_ENV = "production"
PORT = "8080"

[[services.ports]]
handlers = ["http"]
port = 80
force_https = true

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024